version: '3.5'

services:
  s3-storage:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566-4599:4566-4599'
    volumes:
      - './volumes/s3-storage/.init:/docker-entrypoint-initaws.d'
      - './volumes/s3-storage/.localstack:/tmp/localstack'